version: "3"

services:
  steam-review-scraper-workspace:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ../src:/src:cached
      - ../.devcontainer:/config:cached

      # Forwards the local Docker socket to the container.
      - /var/run/docker.sock:/var/run/docker.sock 

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity 
    